#!/bin/bash

export INTERACTIVE=${INTERACTIVE:="true"}
export PVS=${INTERACTIVE:="true"}
export RHUSER=${RHUSER:="$(whoami)"}
export RHPW=${RHPW:=password}
export IP=${IP:="$(ip route get 8.8.8.8 | awk '{print $NF; exit}')"}

## Make the script interactive to set the variables
if [ "$INTERACTIVE" = "true" ]; then

        read -rp "Red Hat Username: ($RHUSER): " choice;
        if [ "$choice" != "" ] ; then
                export RHUSER="$choice";
        fi

        read -rp "Red Hat Password: ($RHPW): " choice;
        if [ "$choice" != "" ] ; then
                export RHPW="$choice";
        fi

fi

echo "******"
echo "* Your DNS IP is $IP "
echo "* Your Red Hat username is $RHUSER "
echo "* Your Red Hat password is $RHPW "
echo "******"



# subscription-manager register
subscription-manager clean
subscription-manager register --username $RHUSER --password $RHPW --auto-attach
subscription-manager refresh
subscription-manager attach --pool=8a85f98b64f079fc0164fb9ca51e054d

subscription-manager repos --disable='*' \
    --enable='rhel-7-server-extras-rpms' \ 
    --enable='rhel-7-server-optional-rpms'

subscription-manager repos --enable="rhel-7-server-rpms" \
    --enable="rhel-7-server-extras-rpms" \
    --enable="rhel-7-server-ose-3.11-rpms" \
    --enable="rhel-7-server-ansible-2.6-rpms"

yum -y install wget git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct
yum -y update
# reboot

yum install -y docker-1.13.1-75.git8633870.el7_5.x86_64

yum -y install openshift-ansible

#------      Update hosts   -----------#
cat <<EOF > /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.100.24.45 installer.vs.com

10.100.24.114 installationhost.vs.com installationhost
10.100.24.114 ceph-dashb.vs.com
10.100.24.116   ocp.vs.com ocp1.vs.com lb lb.vs.com *.apps.datahub.vs.com
10.100.24.116   master01.vs.com master01 ceph-mon01.vs.com mon01 m1
10.100.24.117   master02.vs.com master02 ceph-mon02.vs.com mon02 m2
10.100.24.118   master03.vs.com master03 ceph-mon03.vs.com mon03 m3
10.100.24.119   etcd01.vs.com etcd01 
10.100.24.120   etcd02.vs.com etcd02 
10.100.24.121   etcd03.vs.com etcd03 
10.100.24.122   worker01.vs.com worker01 w1
10.100.24.123   worker02.vs.com worker02 w2
10.100.24.124   worker03.vs.com worker03 w3
10.100.24.125   worker04.vs.com worker04 w4
10.100.24.126   gluster01.vs.com gluster01 ceph-osd01.vs.com osd01
10.100.24.127   gluster02.vs.com gluster02 ceph-osd02.vs.com osd02
10.100.24.128   gluster03.vs.com gluster03 ceph-osd03.vs.com osd03
10.100.24.129   gluster04.vs.com gluster04 ceph-osd04.vs.com osd04
10.100.24.116   datahub.vs.com
10.100.24.116   lb.vs.com
EOF

#------ Update resolv.conf with local DNS -----#
cat <<EOF > /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.100.24.114
nameserver 10.131.236.54
nameserver 8.8.8.8
EOF
